extends Control
class_name Overworld

const DEFAULT_MAP:String = "res://Resources/Maps/UniqueMaps/DEFAULT.tres"

enum PopupModes {
	MARKER
}

@export var mapScreen:MapScreen
@export var popUp:ControlPopup
@export var player:Node2D

func _ready() -> void:
	var marker = mapScreen.MapScreenMarker.construct("TEST", "Autogen", load("res://Assets/UI/GenericUIBackground.png"))
	var markerTWO = mapScreen.MapScreenMarker.construct("TEST2", "Also Autogen", load("res://Assets/UI/GenericUIBackground.png"))
	var marker3 = mapScreen.MapScreenMarker.construct("TEST3", "Also Autogen BUT 3rd", load("res://Assets/UI/GenericUIBackground.png"))
	marker.connectedTo.append("TEST2")
	markerTWO.connectedTo.append("TEST3")
	
	
	marker.stringData = "res://Resources/Maps/UniqueMaps/AutoGenerated.tres"
	markerTWO.stringData = "res://Resources/Maps/UniqueMaps/AutoGenerated.tres"

	mapScreen.add_marker(marker, Vector2(20,50))
	mapScreen.add_marker(markerTWO, Vector2(300,120))
	mapScreen.add_marker(marker3, Vector2(500, 32))

	mapScreen.save_markers()
#	mapScreen.load_markers(mapScreen.DEFAULT_SAVE_PATH)
	
	
	mapScreen.pathing_move_node2d_to_marker($Sprite2D, mapScreen.get_marker_by_identifier("TEST"), mapScreen.get_marker_by_identifier("TEST3"))
	
	load_combat_map(DEFAULT_MAP)

func load_combat_map(mapPath:String):
	var map:Map = load(mapPath)
	Ref.start_combat(map)
	pass

func fill_popup(mode:PopupModes):
	pass
	
func on_marker_selected(marker:MapScreen.MapScreenMarker):
	popUp.pop_up(true, marker.position + mapScreen.position)


#func _gui_input(event: InputEvent) -> void:
#	if event.is_action_pressed("secondary_click"):
#		popUp.pop_up(true, get_global_mouse_position())
