extends Control
class_name Overworld

@export var mapScreen:MapScreen

func _ready() -> void:
	var marker = mapScreen.MapScreenMarker.construct("TEST", "Autogen", load("res://Assets/UI/GenericUIBackground.png"))
	var markerTWO = mapScreen.MapScreenMarker.construct("TEST2", "Also Autogen", load("res://Assets/UI/GenericUIBackground.png"))
	markerTWO.connectedTo.append("TEST")
	
	marker.stringData = "res://Resources/Maps/UniqueMaps/AutoGenerated.tres"
	markerTWO.stringData = "res://Resources/Maps/UniqueMaps/AutoGenerated.tres"

	mapScreen.add_marker(marker, Vector2(20,50))
	mapScreen.add_marker(markerTWO, Vector2(300,120))

	mapScreen.save_markers()
	mapScreen.load_markers(mapScreen.DEFAULT_SAVE_PATH)

func load_combat_map(mapPath:String):
	var map:Map = load(mapPath)
	Ref.start_combat(map)
	pass
